#!/usr/bin/env bash
# Pulls OpenFGA store/model IDs from ConfigMap/harpia-fga-config and writes
# them to local .env files used by host-side development.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FRONTEND_ENV_FILE="$REPO_ROOT/frontend/.env.local"
CONTROL_PLANE_ENV_FILE="$REPO_ROOT/control-plane/.env.local"
CONFIGMAP_NAME="${FGA_CONFIGMAP_NAME:-harpia-fga-config}"
WAIT_SECONDS="${FGA_CONFIG_WAIT_SECONDS:-300}"
POLL_SECONDS="${FGA_CONFIG_POLL_SECONDS:-2}"
TMP_ENV_FILE=""

cleanup_tmp() {
  if [[ -n "$TMP_ENV_FILE" && -e "$TMP_ENV_FILE" ]]; then
    rm -f "$TMP_ENV_FILE"
  fi
}

trap cleanup_tmp EXIT
trap 'cleanup_tmp; exit 130' INT TERM

if ! [[ "$WAIT_SECONDS" =~ ^[0-9]+$ ]] || ! [[ "$POLL_SECONDS" =~ ^[0-9]+$ ]]; then
  echo "ERROR: FGA_CONFIG_WAIT_SECONDS and FGA_CONFIG_POLL_SECONDS must be whole seconds." >&2
  exit 1
fi

if (( 10#$POLL_SECONDS == 0 )); then
  echo "ERROR: FGA_CONFIG_POLL_SECONDS must be greater than zero." >&2
  exit 1
fi

write_env_values() {
  local env_file=$1
  local marker=$2
  shift 2

  local env_dir
  env_dir="$(dirname "$env_file")"
  mkdir -p "$env_dir"

  local keys=()
  local line
  for line in "$@"; do
    keys+=("${line%%=*}")
  done

  TMP_ENV_FILE=$(mktemp "$env_dir/.env.local.tmp.XXXXXX")
  if [[ -e "$env_file" ]]; then
    local existing_mode
    existing_mode=$(stat -c '%a' "$env_file" 2>/dev/null || stat -f '%Lp' "$env_file" 2>/dev/null || true)
    if [[ -n "$existing_mode" ]]; then
      chmod "$existing_mode" "$TMP_ENV_FILE" 2>/dev/null || true
    fi

    local key_pattern
    key_pattern=$(IFS="|"; echo "${keys[*]}")
    awk -v key_pattern="$key_pattern" -v marker="$marker" '
      BEGIN {
        split(key_pattern, names, "|")
        for (i in names) {
          skip[names[i]] = 1
        }
      }
      $0 == "# Generated by " marker " - do not edit these keys by hand." { next }
      /^[A-Za-z_][A-Za-z0-9_]*=/ {
        split($0, pair, "=")
        if (pair[1] in skip) {
          next
        }
      }
      { print }
    ' "$env_file" >"$TMP_ENV_FILE"
  else
    chmod 0644 "$TMP_ENV_FILE" 2>/dev/null || true
  fi

  if [[ -s "$TMP_ENV_FILE" ]]; then
    printf '\n' >>"$TMP_ENV_FILE"
  fi
  printf '# Generated by %s - do not edit these keys by hand.\n' "$marker" >>"$TMP_ENV_FILE"
  for line in "$@"; do
    printf '%s\n' "$line" >>"$TMP_ENV_FILE"
  done

  mv "$TMP_ENV_FILE" "$env_file"
  TMP_ENV_FILE=""
}

STORE_ID=""
AUTH_MODEL_ID=""
API_URL=""
HOST_API_URL=""
DEADLINE=$(( $(date +%s) + 10#$WAIT_SECONDS ))

echo "Waiting up to ${WAIT_SECONDS}s for ConfigMap '$CONFIGMAP_NAME' to publish storeId and authorizationModelId..."
while [[ -z "$STORE_ID" || -z "$AUTH_MODEL_ID" ]]; do
  STORE_ID=$(kubectl get configmap "$CONFIGMAP_NAME" -o jsonpath='{.data.storeId}' 2>/dev/null || true)
  AUTH_MODEL_ID=$(kubectl get configmap "$CONFIGMAP_NAME" -o jsonpath='{.data.authorizationModelId}' 2>/dev/null || true)
  if [[ -n "$STORE_ID" && -n "$AUTH_MODEL_ID" ]]; then
    API_URL=$(kubectl get configmap "$CONFIGMAP_NAME" -o jsonpath='{.data.apiUrl}' 2>/dev/null || true)
    HOST_API_URL=$(kubectl get configmap "$CONFIGMAP_NAME" -o jsonpath='{.data.hostApiUrl}' 2>/dev/null || true)
    break
  fi

  if (( $(date +%s) >= DEADLINE )); then
    echo "ERROR: ConfigMap '$CONFIGMAP_NAME' did not publish OpenFGA IDs within ${WAIT_SECONDS}s." >&2
    echo "Check 'kubectl logs job/openfga-bootstrap' for bootstrap errors." >&2
    exit 1
  fi

  sleep "$POLL_SECONDS"
done

HOST_API_URL=${HOST_API_URL:-http://localhost:8086}
API_URL=${API_URL:-http://openfga:8080}

write_env_values "$FRONTEND_ENV_FILE" "scripts/sync-fga-config.sh" \
  "PUBLIC_OPENFGA_STORE_ID=$STORE_ID" \
  "PUBLIC_OPENFGA_AUTHORIZATION_MODEL_ID=$AUTH_MODEL_ID" \
  "PUBLIC_OPENFGA_API_URL=$HOST_API_URL"

write_env_values "$CONTROL_PLANE_ENV_FILE" "scripts/sync-fga-config.sh" \
  "OPENFGA_STORE_ID=$STORE_ID" \
  "OPENFGA_AUTHORIZATION_MODEL_ID=$AUTH_MODEL_ID" \
  "OPENFGA_API_URL=$HOST_API_URL"

trap - EXIT INT TERM

echo "Wrote $FRONTEND_ENV_FILE"
echo "Wrote $CONTROL_PLANE_ENV_FILE"
echo "  OPENFGA_STORE_ID=$STORE_ID"
echo "  OPENFGA_AUTHORIZATION_MODEL_ID=$AUTH_MODEL_ID"
echo "  OPENFGA_API_URL=$HOST_API_URL"
echo "Cluster API URL from ConfigMap: $API_URL"
