#!/usr/bin/env bash
# Pulls the registered OIDC client_id from ConfigMap/harpia-oidc-config and
# writes it to frontend/.env.local so Vite picks it up as PUBLIC_ZITADEL_CLIENT_ID.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_ROOT/frontend/.env.local"
CONFIGMAP_NAME="${OIDC_CONFIGMAP_NAME:-harpia-oidc-config}"
WAIT_SECONDS="${OIDC_CONFIG_WAIT_SECONDS:-300}"
POLL_SECONDS="${OIDC_CONFIG_POLL_SECONDS:-2}"
TMP_ENV_FILE=""

cleanup_tmp() {
  if [[ -n "$TMP_ENV_FILE" && -e "$TMP_ENV_FILE" ]]; then
    rm -f "$TMP_ENV_FILE"
  fi
}

write_env_values() {
  local env_file=$1
  local marker=$2
  shift 2

  local env_dir
  env_dir="$(dirname "$env_file")"
  mkdir -p "$env_dir"

  local keys=()
  local line
  for line in "$@"; do
    keys+=("${line%%=*}")
  done

  TMP_ENV_FILE=$(mktemp "$env_dir/.env.local.tmp.XXXXXX")
  if [[ -e "$env_file" ]]; then
    local existing_mode
    existing_mode=$(stat -c '%a' "$env_file" 2>/dev/null || stat -f '%Lp' "$env_file" 2>/dev/null || true)
    if [[ -n "$existing_mode" ]]; then
      chmod "$existing_mode" "$TMP_ENV_FILE" 2>/dev/null || true
    fi

    local key_pattern
    key_pattern=$(IFS="|"; echo "${keys[*]}")
    awk -v key_pattern="$key_pattern" -v marker="$marker" '
      BEGIN {
        split(key_pattern, names, "|")
        for (i in names) {
          skip[names[i]] = 1
        }
      }
      $0 == "# Generated by " marker " - do not edit these keys by hand." { next }
      $0 == "# Generated by scripts/sync-oidc-config.sh — do not edit by hand." { next }
      /^[A-Za-z_][A-Za-z0-9_]*=/ {
        split($0, pair, "=")
        if (pair[1] in skip) {
          next
        }
      }
      { print }
    ' "$env_file" >"$TMP_ENV_FILE"
  else
    chmod 0644 "$TMP_ENV_FILE" 2>/dev/null || true
  fi

  if [[ -s "$TMP_ENV_FILE" ]]; then
    printf '\n' >>"$TMP_ENV_FILE"
  fi
  printf '# Generated by %s - do not edit these keys by hand.\n' "$marker" >>"$TMP_ENV_FILE"
  for line in "$@"; do
    printf '%s\n' "$line" >>"$TMP_ENV_FILE"
  done

  mv "$TMP_ENV_FILE" "$env_file"
  TMP_ENV_FILE=""
}

trap cleanup_tmp EXIT
trap 'cleanup_tmp; exit 130' INT TERM

if ! [[ "$WAIT_SECONDS" =~ ^[0-9]+$ ]] || ! [[ "$POLL_SECONDS" =~ ^[0-9]+$ ]]; then
  echo "ERROR: OIDC_CONFIG_WAIT_SECONDS and OIDC_CONFIG_POLL_SECONDS must be whole seconds." >&2
  exit 1
fi

if (( 10#$POLL_SECONDS == 0 )); then
  echo "ERROR: OIDC_CONFIG_POLL_SECONDS must be greater than zero." >&2
  exit 1
fi

CLIENT_ID=""
ISSUER=""
DEADLINE=$(( $(date +%s) + 10#$WAIT_SECONDS ))

echo "Waiting up to ${WAIT_SECONDS}s for ConfigMap '$CONFIGMAP_NAME' to publish clientId..."
while [[ -z "$CLIENT_ID" ]]; do
  CLIENT_ID=$(kubectl get configmap "$CONFIGMAP_NAME" -o jsonpath='{.data.clientId}' 2>/dev/null || true)
  if [[ -n "$CLIENT_ID" ]]; then
    ISSUER=$(kubectl get configmap "$CONFIGMAP_NAME" -o jsonpath='{.data.issuer}' 2>/dev/null || true)
    break
  fi

  if (( $(date +%s) >= DEADLINE )); then
    echo "ERROR: ConfigMap '$CONFIGMAP_NAME' did not publish 'clientId' within ${WAIT_SECONDS}s." >&2
    echo "Check 'kubectl logs job/zitadel-register-client' for registration errors." >&2
    exit 1
  fi

  sleep "$POLL_SECONDS"
done

write_env_values "$ENV_FILE" "scripts/sync-oidc-config.sh" \
  "PUBLIC_ZITADEL_CLIENT_ID=$CLIENT_ID" \
  "PUBLIC_ZITADEL_ISSUER=${ISSUER:-http://localhost:8085}"

trap - EXIT INT TERM

echo "Wrote $ENV_FILE"
echo "  PUBLIC_ZITADEL_CLIENT_ID=$CLIENT_ID"
echo "Tilt restarts the vite local_resource when this file changes."
