#!/usr/bin/env bash
# Pulls the registered OIDC client_id from ConfigMap/harpia-oidc-config and
# writes it to frontend/.env.local so Vite picks it up as PUBLIC_ZITADEL_CLIENT_ID.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_ROOT/frontend/.env.local"
ENV_DIR="$(dirname "$ENV_FILE")"
CONFIGMAP_NAME="${OIDC_CONFIGMAP_NAME:-harpia-oidc-config}"
WAIT_SECONDS="${OIDC_CONFIG_WAIT_SECONDS:-300}"
POLL_SECONDS="${OIDC_CONFIG_POLL_SECONDS:-2}"
TMP_ENV_FILE=""

cleanup_tmp() {
  if [[ -n "$TMP_ENV_FILE" && -e "$TMP_ENV_FILE" ]]; then
    rm -f "$TMP_ENV_FILE"
  fi
}

trap cleanup_tmp EXIT
trap 'cleanup_tmp; exit 130' INT TERM

if ! [[ "$WAIT_SECONDS" =~ ^[0-9]+$ ]] || ! [[ "$POLL_SECONDS" =~ ^[0-9]+$ ]]; then
  echo "ERROR: OIDC_CONFIG_WAIT_SECONDS and OIDC_CONFIG_POLL_SECONDS must be whole seconds." >&2
  exit 1
fi

if (( 10#$POLL_SECONDS == 0 )); then
  echo "ERROR: OIDC_CONFIG_POLL_SECONDS must be greater than zero." >&2
  exit 1
fi

CLIENT_ID=""
ISSUER=""
DEADLINE=$(( $(date +%s) + 10#$WAIT_SECONDS ))

echo "Waiting up to ${WAIT_SECONDS}s for ConfigMap '$CONFIGMAP_NAME' to publish clientId..."
while [[ -z "$CLIENT_ID" ]]; do
  CLIENT_ID=$(kubectl get configmap "$CONFIGMAP_NAME" -o jsonpath='{.data.clientId}' 2>/dev/null || true)
  if [[ -n "$CLIENT_ID" ]]; then
    ISSUER=$(kubectl get configmap "$CONFIGMAP_NAME" -o jsonpath='{.data.issuer}' 2>/dev/null || true)
    break
  fi

  if (( $(date +%s) >= DEADLINE )); then
    echo "ERROR: ConfigMap '$CONFIGMAP_NAME' did not publish 'clientId' within ${WAIT_SECONDS}s." >&2
    echo "Check 'kubectl logs job/zitadel-register-client' for registration errors." >&2
    exit 1
  fi

  sleep "$POLL_SECONDS"
done

TMP_ENV_FILE=$(mktemp "$ENV_DIR/.env.local.tmp.XXXXXX")
if [[ -e "$ENV_FILE" ]]; then
  EXISTING_MODE=$(stat -c '%a' "$ENV_FILE" 2>/dev/null || stat -f '%Lp' "$ENV_FILE" 2>/dev/null || true)
  if [[ -n "$EXISTING_MODE" ]]; then
    chmod "$EXISTING_MODE" "$TMP_ENV_FILE" 2>/dev/null || true
  fi
else
  chmod 0644 "$TMP_ENV_FILE" 2>/dev/null || true
fi

cat >"$TMP_ENV_FILE" <<EOF
# Generated by scripts/sync-oidc-config.sh — do not edit by hand.
PUBLIC_ZITADEL_CLIENT_ID=$CLIENT_ID
PUBLIC_ZITADEL_ISSUER=${ISSUER:-http://localhost:8085}
EOF
mv "$TMP_ENV_FILE" "$ENV_FILE"
TMP_ENV_FILE=""
trap - EXIT INT TERM

echo "Wrote $ENV_FILE"
echo "  PUBLIC_ZITADEL_CLIENT_ID=$CLIENT_ID"
echo "Tilt restarts the vite local_resource when this file changes."
