{{- if .Values.zitadel.enabled }}
{{- $svcName := include "harpia.serviceName" (dict "name" "zitadel" "root" .) }}
{{- $postgresCredentialsSecret := .Values.postgres.credentialsSecret }}
{{- $masterkeySecret := .Values.zitadel.masterkeySecret }}
{{- $machinekeyPVC := printf "%s-machinekey" $svcName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $machinekeyPVC }}
  labels:
    {{- include "harpia.labels" . | nindent 4 }}
    app: {{ $svcName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.zitadel.machinekey.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svcName }}
  labels:
    {{- include "harpia.labels" . | nindent 4 }}
    app: {{ $svcName }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ $svcName }}
  template:
    metadata:
      labels:
        app: {{ $svcName }}
    spec:
      enableServiceLinks: false
      volumes:
        - name: machinekey
          persistentVolumeClaim:
            claimName: {{ $machinekeyPVC }}
      containers:
        - name: zitadel
          image: {{ .Values.zitadel.image | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "start-from-init"
            - "--masterkey"
            - {{ printf "$(%s)" $masterkeySecret.key | quote }}
            - "--tlsMode"
            - "disabled"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: machinekey
              mountPath: /machinekey
          envFrom:
            - secretRef:
                name: {{ $masterkeySecret.name | quote }}
          env:
            - name: ZITADEL_DATABASE_POSTGRES_HOST
              value: {{ include "harpia.serviceName" (dict "name" "postgres" "root" .) | quote }}
            - name: ZITADEL_DATABASE_POSTGRES_PORT
              value: "5432"
            - name: ZITADEL_DATABASE_POSTGRES_DATABASE
              value: "zitadel"
            - name: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $postgresCredentialsSecret.name | quote }}
                  key: {{ $postgresCredentialsSecret.usernameKey | quote }}
            - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $postgresCredentialsSecret.name | quote }}
                  key: {{ $postgresCredentialsSecret.passwordKey | quote }}
            - name: ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $postgresCredentialsSecret.name | quote }}
                  key: {{ $postgresCredentialsSecret.usernameKey | quote }}
            - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $postgresCredentialsSecret.name | quote }}
                  key: {{ $postgresCredentialsSecret.passwordKey | quote }}
            - name: ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE
              value: "disable"
            - name: ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE
              value: "disable"
            - name: ZITADEL_EXTERNALDOMAIN
              value: {{ .Values.zitadel.externalDomain | quote }}
            - name: ZITADEL_EXTERNALPORT
              value: {{ .Values.zitadel.externalPort | quote }}
            - name: ZITADEL_EXTERNALSECURE
              value: {{ .Values.zitadel.externalSecure | quote }}
            - name: ZITADEL_TLS_ENABLED
              value: {{ .Values.zitadel.tlsEnabled | quote }}
            - name: ZITADEL_FIRSTINSTANCE_PATPATH
              value: /machinekey/zitadel-admin-sa.pat
            - name: ZITADEL_FIRSTINSTANCE_ORG_NAME
              value: {{ .Values.zitadel.orgName | quote }}
            - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME
              value: {{ .Values.zitadel.adminUsername | quote }}
            - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD
              value: {{ .Values.zitadel.adminPassword | quote }}
            - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS
              value: {{ .Values.zitadel.adminEmail | quote }}
            - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_VERIFIED
              value: {{ .Values.zitadel.adminEmailVerified | quote }}
            - name: ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME
              value: {{ .Values.zitadel.machineUser.username | quote }}
            - name: ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME
              value: {{ .Values.zitadel.machineUser.name | quote }}
            - name: ZITADEL_FIRSTINSTANCE_ORG_MACHINE_PAT_EXPIRATIONDATE
              value: {{ .Values.zitadel.machineUser.patExpirationDate | quote }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  labels:
    {{- include "harpia.labels" . | nindent 4 }}
    app: {{ $svcName }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ $svcName }}
{{- end }}
